config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  get "/about", to: "sessions#about", as: "about"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :restaurants, only: [:index, :show]

  resources :comments, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurant_cuisines
  has_many :restaurants, through: :restaurant_cuisines
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :location
  has_many :comments
  has_many :users, through: :comments
  has_many :restaurant_cuisines
  has_many :cuisines, through: :restaurant_cuisines

  scope :all_ids, -> { pluck(:id).sort() }
end

app/models/restaurant_cuisine.rb
class RestaurantCuisine < ApplicationRecord
  belongs_to :restaurant
  belongs_to :cuisine
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  belongs_to :avatar
  has_many :comments
  has_many :restaurants, through: :comments

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i.freeze

  validates :first_name, :last_name, :username, :email,
    presence: true

  validates :email,
    format: { with: EMAIL_REGEX }

  validates :username,
    uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def authentication_required
    if !logged_in?
      redirect_to root_path
    end
  end

  def logged_in?
    current_user != nil
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @comment }
    end
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      render json: @comment, status: 201
    else

    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :rating, :user_id, :restaurant_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @locations = Location.all
    @cuisines = Cuisine.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @restaurants.to_json(only: [:id, :name, :description, :phone, :email, :image_url], include: [location: { only: :city}, cuisines: { only: :name }]) }
    end
  end

  def show
    @restaurant_ids = Restaurant.all_ids
    @restaurant = Restaurant.find(params[:id])

    if logged_in?
      @fullname = current_user.full_name
      @avatar_url = current_user.avatar.image_url
    end
    
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @restaurant }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    # home page
  end

  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "success|You are now logged in."
      redirect_to user_path(user)
    else
      flash[:notice] = "danger|Invalid login, please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil;
    flash[:notice] = "success|You have been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authentication_required, except: [:new, :create]
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "success|User #{@user.full_name} was successfully created."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = "success|User #{@user.full_name} was successfully updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.delete

    # remove user session
    session[:user_id] = nil

    flash[:notice] = "success|User #{user.full_name} was successfully deleted."
    redirect_to root_route
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :avatar_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render partial: 'application/error_messages', locals: { object: object }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div class="container">
    <div class="row mb-3">
      <div class="col">
        <div id="error-explanation">
          <h4>
            <%= pluralize(object.errors.size, "error") %> prevented this record from being saved.
          </h4>
          <p>The following fields have problems:</p>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li class="text-danger">
                <%= msg %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5 bg-dark text-white">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Restaurant Explorer © Robert Laws - 2019</p>
    <p>Learn all about your local restaurants.</p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav id="main-navigation" class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Restaurant Explorer</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "User Info", user_path(session[:user_id]), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", logout_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Signup", new_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if !flash[:notice].blank? %>
  <% full_flash = flash[:notice].split("|") %>
  <% if full_flash[0] == "danger" %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= full_flash[1] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% elsif full_flash[0] == "success" %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= full_flash[1] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% else %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <!-- display contnet passed to block without a status flag -->
      <%= full_flash[0] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio Project - Rails and Javascript - Restaurant Explorer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render partial: "layouts/navigation" %>
    </header>

    <%= render partial: "layouts/notice" %>
    
    <div>
      <%= yield %>
    </div>

    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/restaurants/index.html.erb
<main class="container">
  <div class="row mt-5 mb-n3">
    <div class="col">
      <h3>Restaurants</h3>
      <p>Explore all the restaurants in the local area.</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-row align-items-center">
        <div class="col-md-5 my-1">
          <label class="sr-only" for="location_select">Locations</label>
          <%= select_tag 'location_select', options_for_select(@locations.collect{ |l| [l.city, l.city] }), class: "form-control", prompt: "Select a Location"%>
        </div>
        <div class="col-md-2 my-1 text-center">
        OR
        </div>
        <div class="col-md-5 my-1">
          <label class="sr-only" for="cusinie_select">Cuisines</label>
          <%= select_tag 'cuisine_select', options_for_select(@cuisines.collect{ |c| [c.name, c.name] }), class: "form-control", prompt: "Select a Cuisine"%>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div id="all-restaurants" class="col-12">
      <!-- restaurant data will be loaded here -->
    </div>
    <div id="no-restaurants" class="col-12 comments-media">
      No Restaurants Found.
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<main class="container">
  <div class="row mt-5">
    <div class="col">
      <span id="restaurant-all-ids" data-id="<%= @restaurant_ids.join("|") %>"></span>
      <span id="restaurant-id" data-id="<%= @restaurant.id %>"></span>
      <span id="user-fullname" data-value="<%= @fullname %>"></span>
      <span id="user-avatar-url" data-value="<%= @avatar_url %>"></span>
      <h3 id="restaurant-name"></h3>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>

  <div class="row mt-3">
    <div id="single-restaurant" class="col-lg-6 col-md-12">
      <!-- single restaurant data goes here -->
    </div>
    <div class="col-lg-6 col-md-12">
      <h5>Comments</h5>
      <div id="single-restaurant-comments">
        <!-- single restaurant comment data goes here -->
      </div>
      <% if logged_in? %>
        <div class="text-center">
          <i class="fa fa-ellipsis-v fa-2x" aria-hidden="true"></i>
        </div>
        <div class="comments-media mt-2">
          <div id="single-restaurant-new-comment">
            <h5>Add a new comment about this restaurant</h5>
            <form id="add-comment-form" action="/comments" method="post">
              <input type=hidden name="authenticity_token" value="<%= form_authenticity_token %>">
              <input id="form-restaurant-id" type="hidden" name="comment[restaurant_id]" value="">
              <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
              <div class="form-group">
                <label for="body-entry">Comments</label>
                <textarea class="form-control" id="body-entry" name="comment[body]" rows="3"></textarea>
              </div>
              <div class="form-group">
                <label for="rating-entry">Rating</label>
                <select class="form-control" id="rating-entry" name="comment[rating]">
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary">Add Comment</button> <span id="commentErrorText" class="errorText" style="display: none;">Please enter a comment and select a rating</span>
            </form>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control #{@user.errors[:first_name].any? ? 'is-invalid' : ''}", placeholder: "Please enter a first name" %>
</div>

<div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control #{@user.errors[:last_name].any? ? 'is-invalid' : ''}", placeholder: "Please enter a last name" %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control #{@user.errors[:email].any? ? 'is-invalid' : ''}", placeholder: "Please enter an email" %>
</div>

<div class="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control #{@user.errors[:username].any? ? 'is-invalid' : ''}", placeholder: "Please enter a username" %>
</div>

<div class="form-group">
  <%= f.label "Select an Avatar" %><br>
  <%= f.collection_radio_buttons(:avatar_id, Avatar.all, :id, :name) do |a| %>
    <div class="form-check form-check-inline">
      <%= a.label(class: "form-check-label") { a.radio_button(class: "form-check-input") + a.text } %>
    </div>
  <% end %>

</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control #{@user.errors[:password].any? ? 'is-invalid' : ''}", placeholder: "Please enter a password" %>
</div>

<div class="form-group mt-3">
  <%= f.submit submit_text, class: "btn btn-primary" %>
</div>

app/views/users/edit.html.erb
<main class="container">
  <div class="row mt-5">
    <div class="col">
      <h3>Edit Your User Account</h3>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= form_for @user do |f| %>
        <%= render partial: "form", locals: { f: f, submit_text: "Update Account" } %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<main class="container">
  <div class="row mt-5">
    <div class="col">
      <h3>Sign Up</h3>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col">
      <%= form_for @user do |f| %>
        <%= render partial: "form", locals: { f: f, submit_text: "Complete Signup" } %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<main class="container about-content">
  <div class="row mt-5">
    <div class="col">
      <h3>Your Account</h3>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col-4">
      <h5 class="mb-3"><%= @user.full_name %></h5>
      <p><strong>Username</strong>: <%= @user.username %></p>
      <p><strong>Email</strong>: <%= @user.email %></p>
    </div>
    <div class="col-4">
      <%= image_tag @user.avatar.image_url, class: "img-thumbnail" %><br>
      <span>User Avatar</span>
    </div>
  </div>
</div>